[package]
name = "fishgame"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
nanoserde = "0.1"
macroquad = { version = "0.3" }
macroquad-platformer = "0.1"
macroquad-tiled = "0.1"
macroquad-particles = {version = "0.1", features = ["nanoserde"] }

[target.'cfg(target_os = "macos")'.dependencies]
gamepad-rs = { git = "https://github.com/unrust/gamepad-rs.git" }

[patch.crates-io]
macroquad = { git = "https://github.com/not-fl3/macroquad.git", rev = "cc7d9a8" }
macroquad-particles = { git = "https://github.com/not-fl3/macroquad.git", rev = "cc7d9a8" }
macroquad-tiled = { git = "https://github.com/not-fl3/macroquad.git", rev = "cc7d9a8" }

#macroquad = { path = "../macroquad" }
#macroquad-particles = { path = "../macroquad/particles" }
#macroquad-tiled = { path = "../macroquad/tiled" }
