[package]
name = "fishgame"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"

[dependencies]
nanoserde = "0.1"
macroquad = { version = "0.3" }
macroquad-platformer = "0.1"
macroquad-tiled = "0.1"
macroquad-particles = {version = "0.1", features = ["nanoserde"] }
gamepad-rs = { git = "https://github.com/unrust/gamepad-rs.git" }