on: [push, pull_request]

name: Cross-compile

jobs:
  sourcehut:
    name: Push to SourceHut
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2   
        - run: echo $ls
        - run: git status