on:
  push:
    branches:
      - master

name: Cross-compile

jobs:
  sourcehut:
    name: Push to SourceHut
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir ~/.ssh
            echo "${{ secrets.HUT_ID_RSA }}" > ~/.ssh/id_rsa
            echo "${{ secrets.HUT_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
            git push git@git.sr.ht:~not-fl3/FishFight master