on:
  push:
    branches:
      - main

name: SourceHut

jobs:
  sourcehut:
    name: Push to SourceHut
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - run: |
            mkdir ~/.ssh            
            echo "${{ secrets.HUT_ID_RSA }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "${{ secrets.HUT_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
            git push git@git.sr.ht:~not-fl3/FishFight main:master --force
            